#!/bin/bash

################################################################
#### author: slickstack ########################################
#### link: https://slickstack.io ###############################
#### mirror: http://mirrors.slickstack.io/ss-config-example ####
#### path: /var/www/ss-config ##################################
#### purpose: slickstack configuration variables ###############
################################################################

## [wordpress, wplite, bedrock] ##
app="wplite"

## root ssh/sftp user ##
root="root"
rootpass="password"

## sudo ssh/sftp users ##
sudo="example"
sudopass="password"
sudo2="example"
sudo2pass="password"
sudo3="example"
sudo3pass="password"

## non-sudo sftp users chroot jail to /var/www/ ##
user="example"
userpass="password"
user2="example"
user2pass="password"
user3="example"
user3pass="password"

## [example.com, www.example.com, sub.example.com] ##
domain="www.example.com"

## [yes, no] ##
ssl="yes"

## [fastcgi, none] ##
cache="fastcgi"

## database ##
dbname="wordpress"
dbprefix="wp_"
dbrootpass="password"
dbuser="example"
dbuserpass="password"
dbuser2="example"
dbuser2pass="password"
dbuser3="example"
dbuser3pass="password"

## ssl profile ##
country="US"
state="Nevada"
city="Las Vegas"
company="Example LLC"
dept=""

## email api ##
mailserv="sendgrid"
mailsmtp="smtp.sendgrid.net"
mailport="587"
mailalert="user@example.com"
mailalert2="user@example.com"
mailalert3="user@example.com"
mailuser="example"
mailuserpass="password"
mailuser2="example"
mailuser2pass="password"
mailuser3="example"
mailuser3pass="password"

## monit ##
monituser="admin"
monitpass="admin"
